#Calculadora de qualquer valor- limite (40)
n= int(input("Digite um número e verá a sua tabuada: "))
print("--"*10)
print("{} x {} = {}".format(n, 1, n*1))
print("{} x {} = {}".format(n, 2, n*2))
print("{} x {} = {}".format(n, 3, n*3))
print("{} x {} = {}".format(n, 4, n*4))
print("{} x {} = {}".format(n, 5, n*5))
print("{} x {} = {}".format(n, 6, n*6))
print("{} x {} = {}".format(n, 7, n*8))
print("{} x {} = {}".format(n, 9, n*9))
print("{} x {} = {}".format(n, 10, n*10))
print("{} x {} = {}".format(n, 20, n*20))
print("{} x {} = {}".format(n, 30, n*30))
print("{} x {} = {}".format(n, 40, n*40))
print("--"*10)